# -*- coding: utf-8 -*-
"""ML HOUSE PRICE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194TsK1sw1Vv_4BfqMm-O4xUcTgMbmkaa

# Import libraies
"""

import pandas as pd # it is a name given to bar graph #it is given library
import numpy as np # it is a numerical function
import matplotlib.pyplot as plt # it is to plot on graph on y axis & x axis
import seaborn as sns # it is a visualisation
from sklearn.model_selection import train_test_split # It is to split the  data  into training and testing
from sklearn.linear_model import LinearRegression # it is a data tp predict the value is called linear regression
from sklearn.metrics import mean_squared_error, r2_score # it is a matrix which has rows and columns
from sklearn.preprocessing import StandardScaler # It is to remove unwanted value and make it more standard

"""# load datasheet"""

from sklearn.datasets import fetch_california_housing #it is different program from boston

housing = fetch_california_housing() #it is a given program

df = pd.DataFrame(housing.data, columns.feature_names) # it is simmilar to pandas

df['PRICE'] = housing.target # It is a price listed for houses

print("Dataset Shape:", df.shape) # print
print(df.head())

"""# EDA (Optional Visualization)"""

plt.figure(figsize=(10, 6))
sns.histplot(df['PRICE'], bins=30, kde=True) #to  create a histogram graph and plot
plt.title("Distribution of House Prices") #title
plt.show() #display the graph

plt.figure(figsize=(12, 8))
sns.heatmap (df.corr(), annot=True, cmap="coolwarm") #to create a heatmap and coolwarm
plt.title("Feature Correlation Heatmap") # title
plt.show() #display  the heat and cool signatures

"""Feature selection & target"""

X = df.drop('PRICE', axis=1)
y = df['PRICE'] #to give any price